wallpaper {
    monitor = DP-1
    path = /home/valen/Downloads/diinki-aero-main/wallpapers/perfect_hue_17.jpg
    fit_mode = cover
}

# Configuración por si agregas o conectas otro monitor en el futuro
wallpaper {
    monitor =
    path = /home/valen/Downloads/diinki-aero-main/wallpapers/perfect_hue_17.jpg
    fit_mode = cover
}

ipc = on
splash = false
